#!/usr/bin/env bash
#A script that loops best school ten times but at the4th round it says badluck
#and displays good luck for the 8th loop iteration
i="0"
while [ $i -lt 10 ]
do
if [ $i -eq 3 ];
then
    echo "bad luck"
elif  [ $i -eq 7 ];
then
    echo "good luck"
else
    echo "Best School"
fi
i=$((i+1))
done
